export const ENGLISH_TRANSLATIONS = {
  splashTitle: "Sanatan App",
  splashSubtitle:
    "Devotional ringtones, wallpapers, mantras, bhajans, status and TV",
  chooseAccount: "Choose an account",
  continueToSanatan: "to continue to Sanatan",
  selectLanguage: "Select Language",
  underDevelopment: "Under Development",
  drawerTitle: "Sanatan App",
  drawer_d1: "My Profile",
  drawer_d2: "Downloads",
  drawer_d3: "Favorites",
  drawer_d4: "Settings",
  drawer_d5: "Logout",
  helpCenter: "Help Center",
  search: "Search",
  searchPlaceholder: "Search bhajan, mantra, ringtone...",
  shortcut_r: "Ringtone",
  shortcut_a: "Aarti",
  shortcut_tv: "Sanatan TV",
  shortcut_b: "Books",
  heroPage: "Hero Banner",
  heroTitle: "Daily Darshan and Bhakti Media",
  heroSubtitle: "Listen, download and share devotional content.",
  mediaType_wallpaper: "Wallpaper",
  mediaType_song: "Bhajan",
  mediaType_ringtone: "Ringtone",
  feature_f1: "Set Wallpaper",
  feature_f2: "Aarti Bhajan",
  feature_f3: "Mantra and Stuti",
  feature_f4: "AI Status",
  feature_f5: "Today's Horoscope",
  feature_f6: "Set Status",
  trending: "Trending",
  media_w1_title: "Shiv Parivar HD Wallpaper",
  media_w2_title: "Ram Darbar 4K Wallpaper",
  media_s1_title: "Hanuman Chalisa - Female Version",
  media_s2_title: "Shiv Tandav Stotram",
  media_r1_title: "Om Namah Shivay Tone",
  media_r2_title: "Jai Shri Ram Tone",
  download: "Download",
  premiumTitle: "Go Premium",
  premiumText:
    "Unlock ad-free downloads, HD wallpapers and exclusive bhajan collections.",
  premiumUpgradePage: "Premium Upgrade",
  upgradeNow: "Upgrade Now",
  notificationPrompt: "Allow notifications for daily bhakti reminders?",
  allow: "Allow",
  dontAllow: "Don't Allow",
  phoneLoginTitle: "Phone verification",
  phoneLoginSubtitle: "Enter your mobile number to continue.",
  phonePlaceholder: "Mobile number",
  otpPlaceholder: "Enter OTP",
  sendOtp: "Send OTP",
  verifyOtp: "Verify",
  cancel: "Cancel",
  phoneInvalid: "Enter a valid mobile number.",
  otpSendFirst: "Send OTP first.",
  otpInvalid: "Invalid OTP. Please try again.",
  otpDevHint: "Test OTP:",
};

export const HINDI_TRANSLATIONS = {
  ...ENGLISH_TRANSLATIONS,
  splashTitle: "सनातन ऐप",
  splashSubtitle: "भक्ति रिंगटोन, वॉलपेपर, मंत्र, भजन, स्टेटस और टीवी",
  chooseAccount: "खाता चुनें",
  continueToSanatan: "सनातन में आगे बढ़ने के लिए",
  selectLanguage: "भाषा चुनें",
  underDevelopment: "निर्माण जारी है",
  drawerTitle: "सनातन ऐप",
  drawer_d1: "मेरी प्रोफाइल",
  drawer_d2: "डाउनलोड",
  drawer_d3: "पसंदीदा",
  drawer_d4: "सेटिंग्स",
  drawer_d5: "लॉगआउट",
  helpCenter: "सहायता केंद्र",
  search: "खोज",
  searchPlaceholder: "भजन, मंत्र, रिंगटोन खोजें...",
  shortcut_r: "रिंगटोन",
  shortcut_a: "आरती",
  shortcut_tv: "सनातन टीवी",
  shortcut_b: "पुस्तकें",
  heroPage: "मुख्य बैनर",
  heroTitle: "दैनिक दर्शन और भक्ति मीडिया",
  heroSubtitle: "भक्ति सामग्री सुनें, डाउनलोड करें और शेयर करें।",
  mediaType_wallpaper: "वॉलपेपर",
  mediaType_song: "भजन",
  mediaType_ringtone: "रिंगटोन",
  feature_f1: "वॉलपेपर लगाएं",
  feature_f2: "आरती भजन",
  feature_f3: "मंत्र और स्तुति",
  feature_f4: "AI स्टेटस",
  feature_f5: "आज का राशिफल",
  feature_f6: "स्टेटस लगाएं",
  trending: "ट्रेंडिंग",
  media_w1_title: "शिव परिवार HD वॉलपेपर",
  media_w2_title: "राम दरबार 4K वॉलपेपर",
  media_s1_title: "हनुमान चालीसा - फीमेल वर्जन",
  media_s2_title: "शिव तांडव स्तोत्रम्",
  media_r1_title: "ॐ नमः शिवाय टोन",
  media_r2_title: "जय श्री राम टोन",
  download: "डाउनलोड",
  premiumTitle: "प्रीमियम लें",
  premiumText:
    "विज्ञापन-रहित डाउनलोड, HD वॉलपेपर और खास भजन संग्रह अनलॉक करें।",
  premiumUpgradePage: "प्रीमियम अपग्रेड",
  upgradeNow: "अभी अपग्रेड करें",
  notificationPrompt: "दैनिक भक्ति रिमाइंडर के लिए नोटिफिकेशन अनुमति दें?",
  allow: "अनुमति दें",
  dontAllow: "अनुमति नहीं",
  phoneLoginTitle: "??? ??????????",
  phoneLoginSubtitle: "??? ????? ?? ??? ???? ?????? ???? ??????",
  phonePlaceholder: "?????? ????",
  otpPlaceholder: "OTP ?????",
  sendOtp: "OTP ?????",
  verifyOtp: "??????? ????",
  cancel: "???? ????",
  phoneInvalid: "??? ?????? ???? ??????",
  otpSendFirst: "???? OTP ??????",
  otpInvalid: "OTP ??? ??? ??? ????? ?????",
  otpDevHint: "????? OTP:",
};

const LEGACY_TRANSLATIONS = {
  en: ENGLISH_TRANSLATIONS,
  hi: HINDI_TRANSLATIONS,
  l1: HINDI_TRANSLATIONS,
  l2: {
    ...HINDI_TRANSLATIONS,
    splashTitle: "सनातन अॅप",
    splashSubtitle: "भक्ती रिंगटोन, वॉलपेपर, मंत्र, भजन, स्टेटस आणि टीव्ही",
    chooseAccount: "खाते निवडा",
    continueToSanatan: "सनातनमध्ये पुढे जाण्यासाठी",
    selectLanguage: "भाषा निवडा",
    underDevelopment: "काम सुरू आहे",
    drawerTitle: "सनातन अॅप",
    drawer_d1: "माझी प्रोफाइल",
    drawer_d2: "डाउनलोड",
    drawer_d3: "आवडीचे",
    drawer_d4: "सेटिंग्स",
    drawer_d5: "लॉगआउट",
    helpCenter: "मदत केंद्र",
    search: "शोध",
    searchPlaceholder: "भजन, मंत्र, रिंगटोन शोधा...",
    shortcut_r: "रिंगटोन",
    shortcut_a: "आरती",
    shortcut_tv: "सनातन टीव्ही",
    shortcut_b: "पुस्तके",
    heroPage: "मुख्य बॅनर",
    heroTitle: "दैनिक दर्शन आणि भक्ती मीडिया",
    heroSubtitle: "भक्ती सामग्री ऐका, डाउनलोड करा आणि शेअर करा.",
    mediaType_wallpaper: "वॉलपेपर",
    mediaType_song: "भजन",
    mediaType_ringtone: "रिंगटोन",
    feature_f1: "वॉलपेपर लावा",
    feature_f2: "आरती भजन",
    feature_f3: "मंत्र आणि स्तुती",
    feature_f4: "AI स्टेटस",
    feature_f5: "आजचे राशीभविष्य",
    feature_f6: "स्टेटस लावा",
    trending: "ट्रेंडिंग",
    media_w1_title: "शिव परिवार HD वॉलपेपर",
    media_w2_title: "राम दरबार 4K वॉलपेपर",
    media_s1_title: "हनुमान चालीसा - फीमेल वर्जन",
    media_s2_title: "शिव तांडव स्तोत्रम्",
    media_r1_title: "ॐ नमः शिवाय टोन",
    media_r2_title: "जय श्री राम टोन",
    download: "डाउनलोड",
    premiumTitle: "प्रीमियम घ्या",
    premiumText:
      "जाहिरात-मुक्त डाउनलोड, HD वॉलपेपर आणि खास भजन संग्रह अनलॉक करा.",
    premiumUpgradePage: "प्रीमियम अपग्रेड",
    upgradeNow: "आता अपग्रेड करा",
    notificationPrompt: "दैनिक भक्ती स्मरणासाठी नोटिफिकेशन परवानगी द्यायची?",
    allow: "परवानगी द्या",
    dontAllow: "नको",
  },
  l3: {
    ...HINDI_TRANSLATIONS,
    splashTitle: "સનાતન એપ",
    splashSubtitle: "ભક્તિ રિંગટોન, વોલપેપર, મંત્ર, ભજન, સ્ટેટસ અને ટીવી",
    chooseAccount: "એકાઉન્ટ પસંદ કરો",
    continueToSanatan: "સનાતનમાં આગળ વધવા માટે",
    selectLanguage: "ભાષા પસંદ કરો",
    underDevelopment: "કામ ચાલુ છે",
    drawerTitle: "સનાતન એપ",
    drawer_d1: "મારી પ્રોફાઇલ",
    drawer_d2: "ડાઉનલોડ",
    drawer_d3: "મનપસંદ",
    drawer_d4: "સેટિંગ્સ",
    drawer_d5: "લોગઆઉટ",
    helpCenter: "મદદ કેન્દ્ર",
    search: "શોધો",
    searchPlaceholder: "ભજન, મંત્ર, રિંગટોન શોધો...",
    shortcut_r: "રિંગટોન",
    shortcut_a: "આરતી",
    shortcut_tv: "સનાતન ટીવી",
    shortcut_b: "પુસ્તકો",
    heroPage: "મુખ્ય બેનર",
    heroTitle: "દૈનિક દર્શન અને ભક્તિ મીડિયા",
    heroSubtitle: "ભક્તિ સામગ્રી સાંભળો, ડાઉનલોડ કરો અને શેર કરો.",
    mediaType_wallpaper: "વોલપેપર",
    mediaType_song: "ભજન",
    mediaType_ringtone: "રિંગટોન",
    feature_f1: "વોલપેપર સેટ કરો",
    feature_f2: "આરતી ભજન",
    feature_f3: "મંત્ર અને સ્તુતિ",
    feature_f4: "AI સ્ટેટસ",
    feature_f5: "આજનું રાશિફળ",
    feature_f6: "સ્ટેટસ સેટ કરો",
    trending: "ટ્રેન્ડિંગ",
    media_w1_title: "શિવ પરિવાર HD વોલપેપર",
    media_w2_title: "રામ દરબાર 4K વોલપેપર",
    media_s1_title: "હનુમાન ચાલીસા - ફીમેલ વર્ઝન",
    media_s2_title: "શિવ તાંડવ સ્તોત્રમ્",
    media_r1_title: "ૐ નમઃ શિવાય ટોન",
    media_r2_title: "જય શ્રી રામ ટોન",
    download: "ડાઉનલોડ",
    premiumTitle: "પ્રીમિયમ લો",
    premiumText:
      "જાહેરાત-મુક્ત ડાઉનલોડ, HD વોલપેપર અને ખાસ ભજન સંગ્રહ અનલોક કરો.",
    premiumUpgradePage: "પ્રીમિયમ અપગ્રેડ",
    upgradeNow: "હમણાં અપગ્રેડ કરો",
    notificationPrompt: "દૈનિક ભક્તિ રિમાઇન્ડર માટે નોટિફિકેશન મંજૂર કરશો?",
    allow: "મંજૂર",
    dontAllow: "મંજૂર નહીં",
  },
  l4: {
    ...HINDI_TRANSLATIONS,
    splashTitle: "সনাতন অ্যাপ",
    splashSubtitle: "ভক্তি রিংটোন, ওয়ালপেপার, মন্ত্র, ভজন, স্ট্যাটাস ও টিভি",
    chooseAccount: "অ্যাকাউন্ট বেছে নিন",
    continueToSanatan: "সনাতনে এগিয়ে যেতে",
    selectLanguage: "ভাষা নির্বাচন করুন",
    underDevelopment: "কাজ চলছে",
    drawerTitle: "সনাতন অ্যাপ",
    drawer_d1: "আমার প্রোফাইল",
    drawer_d2: "ডাউনলোড",
    drawer_d3: "প্রিয়",
    drawer_d4: "সেটিংস",
    drawer_d5: "লগআউট",
    helpCenter: "সহায়তা কেন্দ্র",
    search: "খুঁজুন",
    searchPlaceholder: "ভজন, মন্ত্র, রিংটোন খুঁজুন...",
    shortcut_r: "রিংটোন",
    shortcut_a: "আরতি",
    shortcut_tv: "সনাতন টিভি",
    shortcut_b: "বই",
    heroPage: "প্রধান ব্যানার",
    heroTitle: "দৈনিক দর্শন ও ভক্তি মিডিয়া",
    heroSubtitle: "ভক্তিমূলক কনটেন্ট শুনুন, ডাউনলোড করুন ও শেয়ার করুন।",
    mediaType_wallpaper: "ওয়ালপেপার",
    mediaType_song: "ভজন",
    mediaType_ringtone: "রিংটোন",
    feature_f1: "ওয়ালপেপার সেট করুন",
    feature_f2: "আরতি ভজন",
    feature_f3: "মন্ত্র ও স্তোত্র",
    feature_f4: "AI স্ট্যাটাস",
    feature_f5: "আজকের রাশিফল",
    feature_f6: "স্ট্যাটাস সেট করুন",
    trending: "ট্রেন্ডিং",
    media_w1_title: "শিব পরিবার HD ওয়ালপেপার",
    media_w2_title: "রাম দরবার 4K ওয়ালপেপার",
    media_s1_title: "হনুমান চালিসা - ফিমেল ভার্সন",
    media_s2_title: "শিব তাণ্ডব স্তোত্রম্",
    media_r1_title: "ওঁ নমঃ শিবায় টোন",
    media_r2_title: "জয় শ্রী রাম টোন",
    download: "ডাউনলোড",
    premiumTitle: "প্রীমিয়াম নিন",
    premiumText:
      "বিজ্ঞাপন-মুক্ত ডাউনলোড, HD ওয়ালপেপার ও বিশেষ ভজন সংগ্রহ আনলক করুন।",
    premiumUpgradePage: "প্রীমিয়াম আপগ্রেড",
    upgradeNow: "এখন আপগ্রেড করুন",
    notificationPrompt: "দৈনিক ভক্তি রিমাইন্ডারের জন্য নোটিফিকেশন দেবেন?",
    allow: "অনুমতি দিন",
    dontAllow: "অনুমতি নয়",
  },
  l5: {
    ...HINDI_TRANSLATIONS,
    splashTitle: "ସନାତନ ଆପ୍",
    selectLanguage: "ଭାଷା ବାଛନ୍ତୁ",
    chooseAccount: "ଖାତା ବାଛନ୍ତୁ",
    searchPlaceholder: "ଭଜନ, ମନ୍ତ୍ର, ରିଙ୍ଗଟୋନ୍ ଖୋଜନ୍ତୁ...",
    drawerTitle: "ସନାତନ ଆପ୍",
    drawer_d1: "ମୋ ପ୍ରୋଫାଇଲ୍",
    drawer_d2: "ଡାଉନଲୋଡ୍",
    drawer_d3: "ପସନ୍ଦ",
    drawer_d4: "ସେଟିଙ୍ଗ୍ସ",
    drawer_d5: "ଲଗଆଉଟ୍",
    helpCenter: "ସହାୟତା କେନ୍ଦ୍ର",
    search: "ଖୋଜନ୍ତୁ",
    shortcut_b: "ପୁସ୍ତକ",
    heroTitle: "ଦୈନିକ ଦର୍ଶନ ଏବଂ ଭକ୍ତି ମିଡିଆ",
    mediaType_wallpaper: "ୱାଲପେପର୍",
    feature_f1: "ୱାଲପେପର୍ ଲଗାନ୍ତୁ",
    feature_f5: "ଆଜିର ରାଶିଫଳ",
    premiumTitle: "ପ୍ରିମିୟମ୍ ନିଅନ୍ତୁ",
    upgradeNow: "ଏବେ ଅପଗ୍ରେଡ୍",
    notificationPrompt: "ଦୈନିକ ଭକ୍ତି ସ୍ମରଣ ପାଇଁ ନୋଟିଫିକେସନ୍ ଦେବେ?",
    underDevelopment: "କାମ ଚାଲିଛି",
  },
  l6: {
    ...HINDI_TRANSLATIONS,
    splashTitle: "சனாதன ஆப்",
    selectLanguage: "மொழியை தேர்வுசெய்க",
    chooseAccount: "கணக்கை தேர்வுசெய்க",
    searchPlaceholder: "பஜன், மந்திரம், ரிங்டோன் தேடுங்கள்...",
    drawerTitle: "சனாதன ஆப்",
    drawer_d1: "என் சுயவிவரம்",
    drawer_d2: "பதிவிறக்கங்கள்",
    drawer_d3: "பிடித்தவை",
    drawer_d4: "அமைப்புகள்",
    drawer_d5: "லாக்அவுட்",
    helpCenter: "உதவி மையம்",
    search: "தேடல்",
    shortcut_b: "புத்தகங்கள்",
    heroTitle: "தினசரி தரிசனம் மற்றும் பக்தி மீடியா",
    mediaType_wallpaper: "வால்பேப்பர்",
    feature_f1: "வால்பேப்பர் அமைக்கவும்",
    feature_f5: "இன்றைய ராசிபலன்",
    premiumTitle: "பிரீமியம் பெறுங்கள்",
    upgradeNow: "இப்போது மேம்படுத்து",
    notificationPrompt:
      "தினசரி பக்தி நினைவூட்டல்களுக்கு அறிவிப்பை அனுமதிக்கவா?",
    underDevelopment: "பணி நடைபெறுகிறது",
  },
  l7: {
    ...HINDI_TRANSLATIONS,
    splashTitle: "సనాతన యాప్",
    selectLanguage: "భాషను ఎంచుకోండి",
    chooseAccount: "ఖాతాను ఎంచుకోండి",
    searchPlaceholder: "భజన్, మంత్రం, రింగ్‌టోన్ శోధించండి...",
    drawerTitle: "సనాతన యాప్",
    drawer_d1: "నా ప్రొఫైల్",
    drawer_d2: "డౌన్‌లోడ్లు",
    drawer_d3: "ఇష్టమైనవి",
    drawer_d4: "సెట్టింగ్స్",
    drawer_d5: "లాగ్అవుట్",
    helpCenter: "సహాయ కేంద్రం",
    search: "శోధించండి",
    shortcut_b: "పుస్తకాలు",
    heroTitle: "రోజువారీ దర్శనం మరియు భక్తి మీడియా",
    mediaType_wallpaper: "వాల్‌పేపర్",
    feature_f1: "వాల్‌పేపర్ సెట్ చేయండి",
    feature_f5: "నేటి రాశిఫలం",
    premiumTitle: "ప్రీమియం పొందండి",
    upgradeNow: "ఇప్పుడే అప్‌గ్రేడ్",
    notificationPrompt: "రోజువారీ భక్తి రిమైండర్లకు నోటిఫికేషన్ అనుమతించాలా?",
    underDevelopment: "పని జరుగుతోంది",
  },
  l8: {
    ...HINDI_TRANSLATIONS,
    splashTitle: "ಸನಾತನ ಆಪ್",
    selectLanguage: "ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ",
    chooseAccount: "ಖಾತೆ ಆಯ್ಕೆಮಾಡಿ",
    searchPlaceholder: "ಭಜನೆ, ಮಂತ್ರ, ರಿಂಗ್‌ಟೋನ್ ಹುಡುಕಿ...",
    drawerTitle: "ಸನಾತನ ಆಪ್",
    drawer_d1: "ನನ್ನ ಪ್ರೊಫೈಲ್",
    drawer_d2: "ಡೌನ್‌ಲೋಡ್‌ಗಳು",
    drawer_d3: "ಇಷ್ಟವಾದವು",
    drawer_d4: "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
    drawer_d5: "ಲಾಗ್ಔಟ್",
    helpCenter: "ಸಹಾಯ ಕೇಂದ್ರ",
    search: "ಹುಡುಕಿ",
    shortcut_b: "ಪುಸ್ತಕಗಳು",
    heroTitle: "ದೈನಂದಿನ ದರ್ಶನ ಮತ್ತು ಭಕ್ತಿ ಮೀಡಿಯಾ",
    mediaType_wallpaper: "ವಾಲ್‌ಪೇಪರ್",
    feature_f1: "ವಾಲ್‌ಪೇಪರ್ ಸೆಟ್ ಮಾಡಿ",
    feature_f5: "ಇಂದಿನ ರಾಶಿಫಲ",
    premiumTitle: "ಪ್ರೀಮಿಯಂ ಪಡೆಯಿರಿ",
    upgradeNow: "ಈಗ ಅಪ್‌ಗ್ರೇಡ್",
    notificationPrompt: "ದೈನಂದಿನ ಭಕ್ತಿ ನೆನಪುಗಳಿಗೆ ನೋಟಿಫಿಕೇಶನ್ ಅನುಮತಿಸಬೇಕೆ?",
    underDevelopment: "ಕೆಲಸ ನಡೆಯುತ್ತಿದೆ",
  },
};

export const resources = {
  en: { translation: ENGLISH_TRANSLATIONS },
  hi: { translation: HINDI_TRANSLATIONS },
  mr: { translation: LEGACY_TRANSLATIONS.l2 },
  gu: { translation: LEGACY_TRANSLATIONS.l3 },
  bn: { translation: LEGACY_TRANSLATIONS.l4 },
  or: { translation: LEGACY_TRANSLATIONS.l5 },
  ta: { translation: LEGACY_TRANSLATIONS.l6 },
  te: { translation: LEGACY_TRANSLATIONS.l7 },
  kn: { translation: LEGACY_TRANSLATIONS.l8 },
};

export const supportedLanguages = Object.keys(resources);
